### ISSUE TITLE
Enum values as keys make using events a compile error

### ISSUE THREAD

**Issue by LordTocs** [j3lte/govee-lan-controller#1]
For reasons I'm not entirely sure about, but I think are related to enums in typescript being both Values and Types. 

Since the keys of `GoveeDeviceEvents` and `GoveeEvents` are enum values, typescript will reject their underlying strings as valid substitutes. So `goveeDevice.on('state_change', ....)` is invalid but `goveeDevice.on(GoveeDeviceEventTypes.StateChange, ...)` is valid. (Despite the two having the same runtime value). 

Unfortunately `GoveeDeviceEventTypes` and `GoveeEventTypes` are not exported so I can't actually use any of the events.

I've worked around the issue by redefining them using `declare module "@j3lte/govee-lan-controller" { <copy paste enums here> }` but using the actual libs' types would be great.

I'm not sure what underlying typescript quirk is the reason for this, or if it's just a problem with my tsconfig. But I thought it was an issue worth bringing up.

**Comment by j3lte** [comment]
It seems those were exported as types, but not referenced. Could you check if it works with the latest version (1.0.2)? I exported the types in index.ts, this should fix the issue...

**Comment by LordTocs** [comment]
Hey sorry I took so long to get back to you, it's been a crazy week.

This absolutely fixed the issue thank you so much! And thanks for building the lib, it's saved me so much work!
